jobs:
  elk:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java (Elasticsearch requires Java)
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

      - name: Download and install Elasticsearch
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.0-linux-x86_64.tar.gz
          tar -xzf elasticsearch-8.10.0-linux-x86_64.tar.gz
          ./elasticsearch-8.10.0/bin/elasticsearch -d

      - name: Wait for Elasticsearch to start
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:9200 | grep -q '"version"'; then
              echo "Elasticsearch is up!"
              break
            else
              echo "Waiting for Elasticsearch..."
              sleep 5
            fi
          done

      - name: Run tests
        run: |
          # your tests here

      - name: Stop Elasticsearch
        run: pkill -f elasticsearch
