name: ELK Stack Test on Windows

on: [push]

jobs:
  elk-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Elasticsearch
        run: |
          Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.2-windows-x86_64.zip -OutFile elasticsearch.zip
          Expand-Archive elasticsearch.zip -DestinationPath elasticsearch

      - name: Start Elasticsearch
        run: |
          Start-Process -NoNewWindow -FilePath "elasticsearch\elasticsearch-8.10.2\bin\elasticsearch.bat"
          Start-Sleep -Seconds 30 # wait for ES to start

      - name: Wait for Elasticsearch health
        run: |
          $health = ""
          for ($i=0; $i -lt 30; $i++) {
            $response = Invoke-RestMethod -Uri http://localhost:9200
            if ($response.status -eq 200) {
              Write-Host "Elasticsearch is up!"
              break
            }
            Start-Sleep -Seconds 5
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      - name: Stop Elasticsearch
        run: |
          Get-Process elasticsearch | Stop-Process -Force
