name: ELK Stack Test on Windows

on: [push]

jobs:
  elk-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Elasticsearch
        run: |
          Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.2-windows-x86_64.zip -OutFile elasticsearch.zip
          Expand-Archive elasticsearch.zip -DestinationPath elasticsearch

      - name: Start Elasticsearch (background job)
        run: |
          Start-Job -ScriptBlock {
            & "elasticsearch\elasticsearch-8.10.2\bin\elasticsearch.bat"
          } | Out-Null
          Start-Sleep -Seconds 40  # Allow ES some time to fully start

      - name: Check if Elasticsearch is up
        run: |
          $maxRetries = 10
          $success = $false

          for ($i = 0; $i -lt $maxRetries; $i++) {
            try {
              $response = Invoke-RestMethod -Uri http://localhost:9200
              if ($response.version) {
                Write-Host "Elasticsearch is up!"
                $success = $true
                break
              }
            } catch {
              Write-Host "Waiting for Elasticsearch..."
              Start-Sleep -Seconds 5
            }
          }

          if (-not $success) {
            throw "Elasticsearch did not start in time."
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      - name: Stop Elasticsearch
        run: |
          Get-Process elasticsearch -ErrorAction SilentlyContinue | Stop-Process -Force
